models:
  small:
    deploy: "local"
    backend: "vllm"
    model_name: "Qwen/Qwen2.5-7B-Instruct"
    tokenizer_name: "Qwen/Qwen2.5-7B-Instruct"
    api_base_url: "http://localhost:8001/v1"
    api_key: "EMPTY"
    max_context_tokens: 32768
    tensor_parallel_size: 1
    dtype: "float16"
  medium:
    deploy: "local"
    backend: "vllm"
    model_name: "Qwen/Qwen3-30B-A3B-Instruct-2507-FP8"
    tokenizer_name: "Qwen/Qwen3-30B-A3B-Instruct-2507-FP8"
    api_base_url: "http://localhost:8002/v1"
    api_key: "EMPTY"
    max_context_tokens: 32768
    tensor_parallel_size: 2
    dtype: "fp8"
  large:
    deploy: "api"
    backend: "openai_compatible"
    model_name: "qwen/qwen3-next-80b-a3b-instruct"
    tokenizer_name: "qwen/qwen3-next-80b-a3b-instruct"
    api_base_url: "https://api.novita.ai/openai/v1"
    api_key: "sk_UGrG5j2iYX4Gkanuz7HdmsB-rFcKiOjvoOV7g58eAJs"
    api_key_env: "DASHSCOPE_API_KEY"
    request_model_name: "qwen/qwen3-next-80b-a3b-instruct"
    max_context_tokens: 262144
    tensor_parallel_size: 1
    dtype: "n/a"
